import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SideNav from "@/components/SideNav";

const roboto = Roboto({
  weight: ['400', '700'], 
  subsets: ['latin', 'cyrillic'], 
  display: 'swap',
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Сведения об образовательной организации",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${roboto.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-row">
        <aside>
            <SideNav/>
        </aside> 
        {children}</body>
    </html>
  );
}
